### ISSUE TITLE
midterm-if.py is ready

### ISSUE THREAD

**Issue by yqin-matc** [madisoncollege-it-programs/python-scripting-yqin-matc#10]
Hi Chris,

This is my midterm-slicing.py.

Thank you.
Best,
Yan

**Comment by yqin-matc** [comment]
Hi Chris,
I've updated the UNIX conversion on Netlab environment, for midterms.
Thank you.
Yan

**Comment by cethenmc** [comment]
Nice work applying what you have learned in this part of the midterm.  There were a few things that prevented you from getting the full score on this part of the midterm.  (1) Unnecessary lines were added to the code:  import testfile and an explicit close statement (1 pt).  Please recall, when opening a file using 'with' notation, it will implicitly close.  Therefore, the explicit textFile.close() is extra noise.  Similarly, if you were using the testfile module while testing, then be sure to remove it in your finish work.  Not sure if you were using it, or if VS Code inserted it automatically when you hit a certain keystroke.  (2) You avoided using elifs which were required (2 pts).  What would happen if a single line included two search words.  For example, change Lanie Whiteland to Kayley Whiteland.  It would make your result 2436, adding that line's value [11] to your total twice.  For every line of the file, you evaluate each keyword every time, insead of just stopping that line once you found one of them.  It diminishes efficiency.  Still a very nice score:  30/33.

**Comment by cethenmc** [comment]
Per our discussion adding 1 pt back for the unnecessary line.
