### ISSUE TITLE
midterm-jpark.py is ready

### ISSUE THREAD

**Issue by yqin-matc** [madisoncollege-it-programs/python-scripting-yqin-matc#11]
Hi Chris,

This is my midterm-jpark.py.

Thank you very much.
Best,
Yan

**Comment by yqin-matc** [comment]
Hi Chris,
I've updated the UNIX conversion on Netlab environment, for midterm-jpark assignment.
Thank you.
Yan

**Comment by cethenmc** [comment]
Nice! 33/33
