### ISSUE TITLE
Ready for grading week14 assignment

### ISSUE THREAD

**Issue by yqin-matc** [madisoncollege-it-programs/python-scripting-yqin-matc#17]
Hi Chris,

This is my week14 assginment for JSON.
It's very interesting on the ipaddress topic. I hope I'm doing it correctly.
Thank you.
Best Regards,
Yan

**Comment by cethenmc** [comment]
Nice work here!  8 out of 8.  Hopefully, you are knocking that final project out.  Everything is due Thursday night.

Best wishes.

Chris
