### ISSUE TITLE
Ready for Grading Final Project

### ISSUE THREAD

**Issue by yqin-matc** [madisoncollege-it-programs/python-scripting-yqin-matc#18]
Hi Chris,

This is my script for the final project. I tried as much as I can. I hope this will work.
Thank you very much for your support.

Best Regards,
Yan

**Comment by cethenmc** [comment]
![image](https://user-images.githubusercontent.com/112707666/208681741-a8252bae-8273-47fb-a949-800941d34b8f.png)
