### ISSUE TITLE
Ready for grading week 6 assignment

### ISSUE THREAD

**Issue by yqin-matc** [madisoncollege-it-programs/python-scripting-yqin-matc#7]
Hi Chris,

This is the my week 6 assignment for flow control.

Thank you.
Yan

**Comment by cethenmc** [comment]
This file cannot be executed from the command line level.  Are you programming on a windows machine and then sending over somehow?  It is an odd error.

student@python-client:~/Repo/Online/python-scripting-yqin-matc/week6$ ./flowcontrol.py 
/usr/bin/env: ‘python3\r’: No such file or directory

Also, Yan, did you intend for choices 1 and 2 after selecting door 3 to render the same result?

student@python-client:~/Repo/Online/python-scripting-yqin-matc/week6$ python3 flowcontrol.py 
You enter a dark room with three doors. 
Do you go through door #1, door #2 or door #3 ?
**-> 3**
You are in front of a hangar

1. Open the door
2. Open the window
**-> 1**
1) It's MS-06S ZAKU II, you find the Char's Zaku!
1) Isn't it beautiful?
student@python-client:~/Repo/Online/python-scripting-yqin-matc/week6$ python3 flowcontrol.py 
You enter a dark room with three doors. 
Do you go through door #1, door #2 or door #3 ?
**-> 3**
You are in front of a hangar

1. Open the door
2. Open the window
**-> 2**
1) It's MS-06S ZAKU II, you find the Char's Zaku!
1) Isn't it beautiful?

student@python-client:~/Repo/Online/python-scripting-yqin-matc/week6$ python3 flowcontrol.py 
You enter a dark room with three doors. 
Do you go through door #1, door #2 or door #3 ?
**-> 3**
You are in front of a hangar

1. Open the door
2. Open the window
**-> 3**
N) You miss the chance to see Char's Mobile Suit.
N) You can try next time
student@python-client:~/Repo/Online/python-scripting-yqin-matc/week6$

**Comment by cethenmc** [comment]
Regarding boolean.py - it also cannot be run from my command line.  I explicitly set the interpreter and it looks good.  I will give a 7 of 8 until it is executable at the command line level.  Thanks.  Chris

**Comment by yqin-matc** [comment]
Hi Chris, 
I've updated the assignments' permission through dos2unix. 
Please let me know if it's working or not.

Thank you.
Yan

**Comment by cethenmc** [comment]
Thank you, Yan!  Both scores are moved to 8 out of 8.
