### ISSUE TITLE
midterm-slicing.py is ready

### ISSUE THREAD

**Issue by yqin-matc** [madisoncollege-it-programs/python-scripting-yqin-matc#9]
Hi Chris,

This is my midterm-slicing.py.

Thank you.
Yan

**Comment by yqin-matc** [comment]
Hi Chris,
I've updated the UNIX conversion on Netlab environment, for midterms.
Thank you.
Yan

**Comment by cethenmc** [comment]
Wow!  Beautiful work!  I only have one point.  Line 14 was an unnecessary join statement.  You could have just set quote = val1 to render the same result.  Val1 was already a string, so there is not value in executing the joining 33/34
